version: 2
jobs:
  build:
    docker:
      - image: zondax/circleci:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: conan config install https://github.com/conan-io/conanclientcert.git
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      # Unfortunately need to disable leak sanitizer https://github.com/google/sanitizers/issues/916
      # Still run all other ASAN components
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_ledger:
    docker:
      - image: zondax/builder-bolos:latest
    working_directory: ~/project
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      # Docker entrypoint is not considered
      - run: git submodule update --init --recursive
      - run:
          name: Build Standard app
          command: |
            source /home/zondax/.cargo/env
            make

  build_ledger_val:
    docker:
      - image: zondax/builder-bolos:latest
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      # Docker entrypoint is not considered
      - run: git submodule update --init --recursive
      - run:
          name: Clean
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make clean
      - run:
          name: Build Validator app
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            COIN=oasis_validator make

  test_zemu:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.15.0
            nvm use 14.15.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make buildS
            make clean
            make buildX
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_test

  test_zemu_adr0008-0:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.15.0
            nvm use 14.15.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make buildS
            make clean
            make buildX
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            COIN=adr0008-0 make zemu_test

  test_zemu_adr0008-0-oasis:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.15.0
            nvm use 14.15.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make buildS
            make clean
            make buildX
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            COIN=adr0008-0-oasis make zemu_test

  test_zemu_adr0008-5:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.15.0
            nvm use 14.15.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make buildS
            make clean
            make buildX
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            COIN=adr0008-5 make zemu_test

  test_zemu_val:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.15.0
            nvm use 14.15.0
            npm install -g yarn
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Build Ledger Validator app
          command: |
            make build_val
      - run:
          name: Run zemu tests for Validator app
          command: |
            nvm use 14.15.0
            export PATH=~/.cargo/bin:$PATH
            COIN=val make zemu_test

  build_package:
    docker:
      - image: zondax/builder-bolos:latest
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Build
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make
      - run: /home/zondax/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(/home/zondax/project/app/pkg/installer_s.sh version) /home/zondax/project/app/pkg/installer_s.sh

  build_package_validator:
    docker:
      - image: zondax/builder-bolos:latest
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Build
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            COIN=oasis_validator make
      - run: /home/zondax/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(/home/zondax/project/app/pkg/installer_s.sh version) /home/zondax/project/app/pkg/installer_validator_s.sh

workflows:
  version: 2

  default:
    jobs:
      - build
      - build_ledger
      - build_ledger_val
      - test_zemu
      - test_zemu_adr0008-0
      - test_zemu_adr0008-5
      - test_zemu_adr0008-0-oasis
      - test_zemu_val
      - build_package:
          requires:
            - build
            - build_ledger
            - build_ledger_val
            - test_zemu
            - test_zemu_val
            - test_zemu_adr0008-0
            - test_zemu_adr0008-5
            - test_zemu_adr0008-0-oasis
          filters:
            branches:
              only:
                - master
      - build_package_validator:
          requires:
            - build
            - build_ledger
            - build_ledger_val
            - test_zemu
            - test_zemu_adr0008-0
            - test_zemu_adr0008-5
            - test_zemu_adr0008-0-oasis
            - test_zemu_val
          filters:
            branches:
              only:
                - master
